package com.dualwisdom.om.dao;

import com.dualwisdom.om.pojo.OrderMain;
import com.dualwisdom.om.pojo.OrderMainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int countByExample(OrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int deleteByExample(OrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String orderKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int insert(OrderMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int insertSelective(OrderMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    List<OrderMain> selectByExample(OrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    OrderMain selectByPrimaryKey(String orderKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") OrderMain record, @Param("example") OrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int updateByExample(@Param("record") OrderMain record, @Param("example") OrderMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(OrderMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int updateByPrimaryKey(OrderMain record);
}