package com.dualwisdom.om.dao;

import com.dualwisdom.om.pojo.OrderDetail;
import com.dualwisdom.om.pojo.OrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int countByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    int updateByExample(@Param("record") OrderDetail record, @Param("example") OrderDetailExample example);
}