package com.dualwisdom.om.pojo;

import java.util.Date;

public class OrderMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String orderKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.EXTERN_ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String externOrderKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.CUSTOMER_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String customerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.CUSTOMER_NAME
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.SHIP_TO_ADDR1
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String shipToAddr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.SHIP_TO_ADDR2
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String shipToAddr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.SHIP_TO_ADDR3
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String shipToAddr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.SHIP_TO_ADDR4
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String shipToAddr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.SHIP_TO_ADDR5
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String shipToAddr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.ETD
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private Date etd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.ETA
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private Date eta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.INVOICE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private Date invoiceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.INVOICE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String invoiceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.CREATION_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.CREATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_MAIN.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String lastUpdatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.ORDER_KEY
     *
     * @return the value of public.ORDER_MAIN.ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getOrderKey() {
        return orderKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.ORDER_KEY
     *
     * @param orderKey the value for public.ORDER_MAIN.ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setOrderKey(String orderKey) {
        this.orderKey = orderKey == null ? null : orderKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.EXTERN_ORDER_KEY
     *
     * @return the value of public.ORDER_MAIN.EXTERN_ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getExternOrderKey() {
        return externOrderKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.EXTERN_ORDER_KEY
     *
     * @param externOrderKey the value for public.ORDER_MAIN.EXTERN_ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setExternOrderKey(String externOrderKey) {
        this.externOrderKey = externOrderKey == null ? null : externOrderKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.CUSTOMER_NUMBER
     *
     * @return the value of public.ORDER_MAIN.CUSTOMER_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.CUSTOMER_NUMBER
     *
     * @param customerNumber the value for public.ORDER_MAIN.CUSTOMER_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber == null ? null : customerNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.CUSTOMER_NAME
     *
     * @return the value of public.ORDER_MAIN.CUSTOMER_NAME
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.CUSTOMER_NAME
     *
     * @param customerName the value for public.ORDER_MAIN.CUSTOMER_NAME
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR1
     *
     * @return the value of public.ORDER_MAIN.SHIP_TO_ADDR1
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getShipToAddr1() {
        return shipToAddr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR1
     *
     * @param shipToAddr1 the value for public.ORDER_MAIN.SHIP_TO_ADDR1
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setShipToAddr1(String shipToAddr1) {
        this.shipToAddr1 = shipToAddr1 == null ? null : shipToAddr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR2
     *
     * @return the value of public.ORDER_MAIN.SHIP_TO_ADDR2
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getShipToAddr2() {
        return shipToAddr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR2
     *
     * @param shipToAddr2 the value for public.ORDER_MAIN.SHIP_TO_ADDR2
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setShipToAddr2(String shipToAddr2) {
        this.shipToAddr2 = shipToAddr2 == null ? null : shipToAddr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR3
     *
     * @return the value of public.ORDER_MAIN.SHIP_TO_ADDR3
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getShipToAddr3() {
        return shipToAddr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR3
     *
     * @param shipToAddr3 the value for public.ORDER_MAIN.SHIP_TO_ADDR3
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setShipToAddr3(String shipToAddr3) {
        this.shipToAddr3 = shipToAddr3 == null ? null : shipToAddr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR4
     *
     * @return the value of public.ORDER_MAIN.SHIP_TO_ADDR4
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getShipToAddr4() {
        return shipToAddr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR4
     *
     * @param shipToAddr4 the value for public.ORDER_MAIN.SHIP_TO_ADDR4
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setShipToAddr4(String shipToAddr4) {
        this.shipToAddr4 = shipToAddr4 == null ? null : shipToAddr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR5
     *
     * @return the value of public.ORDER_MAIN.SHIP_TO_ADDR5
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getShipToAddr5() {
        return shipToAddr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.SHIP_TO_ADDR5
     *
     * @param shipToAddr5 the value for public.ORDER_MAIN.SHIP_TO_ADDR5
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setShipToAddr5(String shipToAddr5) {
        this.shipToAddr5 = shipToAddr5 == null ? null : shipToAddr5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.ETD
     *
     * @return the value of public.ORDER_MAIN.ETD
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Date getEtd() {
        return etd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.ETD
     *
     * @param etd the value for public.ORDER_MAIN.ETD
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setEtd(Date etd) {
        this.etd = etd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.ETA
     *
     * @return the value of public.ORDER_MAIN.ETA
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Date getEta() {
        return eta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.ETA
     *
     * @param eta the value for public.ORDER_MAIN.ETA
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setEta(Date eta) {
        this.eta = eta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.INVOICE_DATE
     *
     * @return the value of public.ORDER_MAIN.INVOICE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Date getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.INVOICE_DATE
     *
     * @param invoiceDate the value for public.ORDER_MAIN.INVOICE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.INVOICE_NUMBER
     *
     * @return the value of public.ORDER_MAIN.INVOICE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.INVOICE_NUMBER
     *
     * @param invoiceNumber the value for public.ORDER_MAIN.INVOICE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber == null ? null : invoiceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.CREATION_DATE
     *
     * @return the value of public.ORDER_MAIN.CREATION_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.CREATION_DATE
     *
     * @param creationDate the value for public.ORDER_MAIN.CREATION_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.CREATED_BY
     *
     * @return the value of public.ORDER_MAIN.CREATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.CREATED_BY
     *
     * @param createdBy the value for public.ORDER_MAIN.CREATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.LAST_UPDATE_DATE
     *
     * @return the value of public.ORDER_MAIN.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for public.ORDER_MAIN.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_MAIN.LAST_UPDATED_BY
     *
     * @return the value of public.ORDER_MAIN.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_MAIN.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for public.ORDER_MAIN.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy == null ? null : lastUpdatedBy.trim();
    }
}