package com.dualwisdom.om.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public OrderDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderDetailKeyIsNull() {
            addCriterion("\"ORDER_DETAIL_KEY\" is null");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyIsNotNull() {
            addCriterion("\"ORDER_DETAIL_KEY\" is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyEqualTo(String value) {
            addCriterion("\"ORDER_DETAIL_KEY\" =", value, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyNotEqualTo(String value) {
            addCriterion("\"ORDER_DETAIL_KEY\" <>", value, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyGreaterThan(String value) {
            addCriterion("\"ORDER_DETAIL_KEY\" >", value, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyGreaterThanOrEqualTo(String value) {
            addCriterion("\"ORDER_DETAIL_KEY\" >=", value, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyLessThan(String value) {
            addCriterion("\"ORDER_DETAIL_KEY\" <", value, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyLessThanOrEqualTo(String value) {
            addCriterion("\"ORDER_DETAIL_KEY\" <=", value, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyLike(String value) {
            addCriterion("\"ORDER_DETAIL_KEY\" like", value, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyNotLike(String value) {
            addCriterion("\"ORDER_DETAIL_KEY\" not like", value, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyIn(List<String> values) {
            addCriterion("\"ORDER_DETAIL_KEY\" in", values, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyNotIn(List<String> values) {
            addCriterion("\"ORDER_DETAIL_KEY\" not in", values, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyBetween(String value1, String value2) {
            addCriterion("\"ORDER_DETAIL_KEY\" between", value1, value2, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderDetailKeyNotBetween(String value1, String value2) {
            addCriterion("\"ORDER_DETAIL_KEY\" not between", value1, value2, "orderDetailKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyIsNull() {
            addCriterion("\"ORDER_KEY\" is null");
            return (Criteria) this;
        }

        public Criteria andOrderKeyIsNotNull() {
            addCriterion("\"ORDER_KEY\" is not null");
            return (Criteria) this;
        }

        public Criteria andOrderKeyEqualTo(String value) {
            addCriterion("\"ORDER_KEY\" =", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyNotEqualTo(String value) {
            addCriterion("\"ORDER_KEY\" <>", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyGreaterThan(String value) {
            addCriterion("\"ORDER_KEY\" >", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyGreaterThanOrEqualTo(String value) {
            addCriterion("\"ORDER_KEY\" >=", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyLessThan(String value) {
            addCriterion("\"ORDER_KEY\" <", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyLessThanOrEqualTo(String value) {
            addCriterion("\"ORDER_KEY\" <=", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyLike(String value) {
            addCriterion("\"ORDER_KEY\" like", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyNotLike(String value) {
            addCriterion("\"ORDER_KEY\" not like", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyIn(List<String> values) {
            addCriterion("\"ORDER_KEY\" in", values, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyNotIn(List<String> values) {
            addCriterion("\"ORDER_KEY\" not in", values, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyBetween(String value1, String value2) {
            addCriterion("\"ORDER_KEY\" between", value1, value2, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyNotBetween(String value1, String value2) {
            addCriterion("\"ORDER_KEY\" not between", value1, value2, "orderKey");
            return (Criteria) this;
        }

        public Criteria andLineNumberIsNull() {
            addCriterion("\"LINE_NUMBER\" is null");
            return (Criteria) this;
        }

        public Criteria andLineNumberIsNotNull() {
            addCriterion("\"LINE_NUMBER\" is not null");
            return (Criteria) this;
        }

        public Criteria andLineNumberEqualTo(Short value) {
            addCriterion("\"LINE_NUMBER\" =", value, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberNotEqualTo(Short value) {
            addCriterion("\"LINE_NUMBER\" <>", value, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberGreaterThan(Short value) {
            addCriterion("\"LINE_NUMBER\" >", value, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberGreaterThanOrEqualTo(Short value) {
            addCriterion("\"LINE_NUMBER\" >=", value, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberLessThan(Short value) {
            addCriterion("\"LINE_NUMBER\" <", value, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberLessThanOrEqualTo(Short value) {
            addCriterion("\"LINE_NUMBER\" <=", value, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberIn(List<Short> values) {
            addCriterion("\"LINE_NUMBER\" in", values, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberNotIn(List<Short> values) {
            addCriterion("\"LINE_NUMBER\" not in", values, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberBetween(Short value1, Short value2) {
            addCriterion("\"LINE_NUMBER\" between", value1, value2, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andLineNumberNotBetween(Short value1, Short value2) {
            addCriterion("\"LINE_NUMBER\" not between", value1, value2, "lineNumber");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyIsNull() {
            addCriterion("\"EXTERN_ORDER_KEY\" is null");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyIsNotNull() {
            addCriterion("\"EXTERN_ORDER_KEY\" is not null");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyEqualTo(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" =", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyNotEqualTo(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" <>", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyGreaterThan(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" >", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyGreaterThanOrEqualTo(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" >=", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyLessThan(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" <", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyLessThanOrEqualTo(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" <=", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyLike(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" like", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyNotLike(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" not like", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyIn(List<String> values) {
            addCriterion("\"EXTERN_ORDER_KEY\" in", values, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyNotIn(List<String> values) {
            addCriterion("\"EXTERN_ORDER_KEY\" not in", values, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyBetween(String value1, String value2) {
            addCriterion("\"EXTERN_ORDER_KEY\" between", value1, value2, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyNotBetween(String value1, String value2) {
            addCriterion("\"EXTERN_ORDER_KEY\" not between", value1, value2, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberIsNull() {
            addCriterion("\"EXTERN_LINE_NUMBER\" is null");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberIsNotNull() {
            addCriterion("\"EXTERN_LINE_NUMBER\" is not null");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberEqualTo(String value) {
            addCriterion("\"EXTERN_LINE_NUMBER\" =", value, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberNotEqualTo(String value) {
            addCriterion("\"EXTERN_LINE_NUMBER\" <>", value, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberGreaterThan(String value) {
            addCriterion("\"EXTERN_LINE_NUMBER\" >", value, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberGreaterThanOrEqualTo(String value) {
            addCriterion("\"EXTERN_LINE_NUMBER\" >=", value, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberLessThan(String value) {
            addCriterion("\"EXTERN_LINE_NUMBER\" <", value, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberLessThanOrEqualTo(String value) {
            addCriterion("\"EXTERN_LINE_NUMBER\" <=", value, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberLike(String value) {
            addCriterion("\"EXTERN_LINE_NUMBER\" like", value, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberNotLike(String value) {
            addCriterion("\"EXTERN_LINE_NUMBER\" not like", value, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberIn(List<String> values) {
            addCriterion("\"EXTERN_LINE_NUMBER\" in", values, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberNotIn(List<String> values) {
            addCriterion("\"EXTERN_LINE_NUMBER\" not in", values, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberBetween(String value1, String value2) {
            addCriterion("\"EXTERN_LINE_NUMBER\" between", value1, value2, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andExternLineNumberNotBetween(String value1, String value2) {
            addCriterion("\"EXTERN_LINE_NUMBER\" not between", value1, value2, "externLineNumber");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("\"ITEM_NAME\" is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("\"ITEM_NAME\" is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("\"ITEM_NAME\" =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("\"ITEM_NAME\" <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("\"ITEM_NAME\" >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("\"ITEM_NAME\" >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("\"ITEM_NAME\" <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("\"ITEM_NAME\" <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("\"ITEM_NAME\" like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("\"ITEM_NAME\" not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("\"ITEM_NAME\" in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("\"ITEM_NAME\" not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("\"ITEM_NAME\" between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("\"ITEM_NAME\" not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andOrderQtyIsNull() {
            addCriterion("\"ORDER_QTY\" is null");
            return (Criteria) this;
        }

        public Criteria andOrderQtyIsNotNull() {
            addCriterion("\"ORDER_QTY\" is not null");
            return (Criteria) this;
        }

        public Criteria andOrderQtyEqualTo(BigDecimal value) {
            addCriterion("\"ORDER_QTY\" =", value, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyNotEqualTo(BigDecimal value) {
            addCriterion("\"ORDER_QTY\" <>", value, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyGreaterThan(BigDecimal value) {
            addCriterion("\"ORDER_QTY\" >", value, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"ORDER_QTY\" >=", value, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyLessThan(BigDecimal value) {
            addCriterion("\"ORDER_QTY\" <", value, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"ORDER_QTY\" <=", value, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyIn(List<BigDecimal> values) {
            addCriterion("\"ORDER_QTY\" in", values, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyNotIn(List<BigDecimal> values) {
            addCriterion("\"ORDER_QTY\" not in", values, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"ORDER_QTY\" between", value1, value2, "orderQty");
            return (Criteria) this;
        }

        public Criteria andOrderQtyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"ORDER_QTY\" not between", value1, value2, "orderQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyIsNull() {
            addCriterion("\"SHIPPED_QTY\" is null");
            return (Criteria) this;
        }

        public Criteria andShippedQtyIsNotNull() {
            addCriterion("\"SHIPPED_QTY\" is not null");
            return (Criteria) this;
        }

        public Criteria andShippedQtyEqualTo(BigDecimal value) {
            addCriterion("\"SHIPPED_QTY\" =", value, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyNotEqualTo(BigDecimal value) {
            addCriterion("\"SHIPPED_QTY\" <>", value, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyGreaterThan(BigDecimal value) {
            addCriterion("\"SHIPPED_QTY\" >", value, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"SHIPPED_QTY\" >=", value, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyLessThan(BigDecimal value) {
            addCriterion("\"SHIPPED_QTY\" <", value, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"SHIPPED_QTY\" <=", value, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyIn(List<BigDecimal> values) {
            addCriterion("\"SHIPPED_QTY\" in", values, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyNotIn(List<BigDecimal> values) {
            addCriterion("\"SHIPPED_QTY\" not in", values, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"SHIPPED_QTY\" between", value1, value2, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andShippedQtyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"SHIPPED_QTY\" not between", value1, value2, "shippedQty");
            return (Criteria) this;
        }

        public Criteria andUomIsNull() {
            addCriterion("\"UOM\" is null");
            return (Criteria) this;
        }

        public Criteria andUomIsNotNull() {
            addCriterion("\"UOM\" is not null");
            return (Criteria) this;
        }

        public Criteria andUomEqualTo(String value) {
            addCriterion("\"UOM\" =", value, "uom");
            return (Criteria) this;
        }

        public Criteria andUomNotEqualTo(String value) {
            addCriterion("\"UOM\" <>", value, "uom");
            return (Criteria) this;
        }

        public Criteria andUomGreaterThan(String value) {
            addCriterion("\"UOM\" >", value, "uom");
            return (Criteria) this;
        }

        public Criteria andUomGreaterThanOrEqualTo(String value) {
            addCriterion("\"UOM\" >=", value, "uom");
            return (Criteria) this;
        }

        public Criteria andUomLessThan(String value) {
            addCriterion("\"UOM\" <", value, "uom");
            return (Criteria) this;
        }

        public Criteria andUomLessThanOrEqualTo(String value) {
            addCriterion("\"UOM\" <=", value, "uom");
            return (Criteria) this;
        }

        public Criteria andUomLike(String value) {
            addCriterion("\"UOM\" like", value, "uom");
            return (Criteria) this;
        }

        public Criteria andUomNotLike(String value) {
            addCriterion("\"UOM\" not like", value, "uom");
            return (Criteria) this;
        }

        public Criteria andUomIn(List<String> values) {
            addCriterion("\"UOM\" in", values, "uom");
            return (Criteria) this;
        }

        public Criteria andUomNotIn(List<String> values) {
            addCriterion("\"UOM\" not in", values, "uom");
            return (Criteria) this;
        }

        public Criteria andUomBetween(String value1, String value2) {
            addCriterion("\"UOM\" between", value1, value2, "uom");
            return (Criteria) this;
        }

        public Criteria andUomNotBetween(String value1, String value2) {
            addCriterion("\"UOM\" not between", value1, value2, "uom");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("\"CREATION_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("\"CREATION_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("\"CREATION_DATE\" =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("\"CREATION_DATE\" <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("\"CREATION_DATE\" >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"CREATION_DATE\" >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("\"CREATION_DATE\" <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("\"CREATION_DATE\" <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("\"CREATION_DATE\" in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("\"CREATION_DATE\" not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("\"CREATION_DATE\" between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("\"CREATION_DATE\" not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("\"CREATED_BY\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("\"CREATED_BY\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("\"CREATED_BY\" =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("\"CREATED_BY\" <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("\"CREATED_BY\" >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("\"CREATED_BY\" >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("\"CREATED_BY\" <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("\"CREATED_BY\" <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("\"CREATED_BY\" like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("\"CREATED_BY\" not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("\"CREATED_BY\" in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("\"CREATED_BY\" not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("\"CREATED_BY\" between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("\"CREATED_BY\" not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("\"LAST_UPDATE_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("\"LAST_UPDATE_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("\"LAST_UPDATE_DATE\" in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("\"LAST_UPDATE_DATE\" not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("\"LAST_UPDATE_DATE\" between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("\"LAST_UPDATE_DATE\" not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNull() {
            addCriterion("\"LAST_UPDATED_BY\" is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNotNull() {
            addCriterion("\"LAST_UPDATED_BY\" is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByEqualTo(String value) {
            addCriterion("\"LAST_UPDATED_BY\" =", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotEqualTo(String value) {
            addCriterion("\"LAST_UPDATED_BY\" <>", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThan(String value) {
            addCriterion("\"LAST_UPDATED_BY\" >", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("\"LAST_UPDATED_BY\" >=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThan(String value) {
            addCriterion("\"LAST_UPDATED_BY\" <", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("\"LAST_UPDATED_BY\" <=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLike(String value) {
            addCriterion("\"LAST_UPDATED_BY\" like", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotLike(String value) {
            addCriterion("\"LAST_UPDATED_BY\" not like", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIn(List<String> values) {
            addCriterion("\"LAST_UPDATED_BY\" in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotIn(List<String> values) {
            addCriterion("\"LAST_UPDATED_BY\" not in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByBetween(String value1, String value2) {
            addCriterion("\"LAST_UPDATED_BY\" between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotBetween(String value1, String value2) {
            addCriterion("\"LAST_UPDATED_BY\" not between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.ORDER_DETAIL
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}