package com.dualwisdom.om.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.ORDER_DETAIL_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String orderDetailKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String orderKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.LINE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private Short lineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.EXTERN_ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String externOrderKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.EXTERN_LINE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String externLineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.ITEM_NAME
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.ORDER_QTY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private BigDecimal orderQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.SHIPPED_QTY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private BigDecimal shippedQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.UOM
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String uom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.CREATION_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.CREATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ORDER_DETAIL.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    private String lastUpdatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.ORDER_DETAIL_KEY
     *
     * @return the value of public.ORDER_DETAIL.ORDER_DETAIL_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getOrderDetailKey() {
        return orderDetailKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.ORDER_DETAIL_KEY
     *
     * @param orderDetailKey the value for public.ORDER_DETAIL.ORDER_DETAIL_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setOrderDetailKey(String orderDetailKey) {
        this.orderDetailKey = orderDetailKey == null ? null : orderDetailKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.ORDER_KEY
     *
     * @return the value of public.ORDER_DETAIL.ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getOrderKey() {
        return orderKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.ORDER_KEY
     *
     * @param orderKey the value for public.ORDER_DETAIL.ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setOrderKey(String orderKey) {
        this.orderKey = orderKey == null ? null : orderKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.LINE_NUMBER
     *
     * @return the value of public.ORDER_DETAIL.LINE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Short getLineNumber() {
        return lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.LINE_NUMBER
     *
     * @param lineNumber the value for public.ORDER_DETAIL.LINE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setLineNumber(Short lineNumber) {
        this.lineNumber = lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.EXTERN_ORDER_KEY
     *
     * @return the value of public.ORDER_DETAIL.EXTERN_ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getExternOrderKey() {
        return externOrderKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.EXTERN_ORDER_KEY
     *
     * @param externOrderKey the value for public.ORDER_DETAIL.EXTERN_ORDER_KEY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setExternOrderKey(String externOrderKey) {
        this.externOrderKey = externOrderKey == null ? null : externOrderKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.EXTERN_LINE_NUMBER
     *
     * @return the value of public.ORDER_DETAIL.EXTERN_LINE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getExternLineNumber() {
        return externLineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.EXTERN_LINE_NUMBER
     *
     * @param externLineNumber the value for public.ORDER_DETAIL.EXTERN_LINE_NUMBER
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setExternLineNumber(String externLineNumber) {
        this.externLineNumber = externLineNumber == null ? null : externLineNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.ITEM_NAME
     *
     * @return the value of public.ORDER_DETAIL.ITEM_NAME
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.ITEM_NAME
     *
     * @param itemName the value for public.ORDER_DETAIL.ITEM_NAME
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.ORDER_QTY
     *
     * @return the value of public.ORDER_DETAIL.ORDER_QTY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public BigDecimal getOrderQty() {
        return orderQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.ORDER_QTY
     *
     * @param orderQty the value for public.ORDER_DETAIL.ORDER_QTY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setOrderQty(BigDecimal orderQty) {
        this.orderQty = orderQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.SHIPPED_QTY
     *
     * @return the value of public.ORDER_DETAIL.SHIPPED_QTY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public BigDecimal getShippedQty() {
        return shippedQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.SHIPPED_QTY
     *
     * @param shippedQty the value for public.ORDER_DETAIL.SHIPPED_QTY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setShippedQty(BigDecimal shippedQty) {
        this.shippedQty = shippedQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.UOM
     *
     * @return the value of public.ORDER_DETAIL.UOM
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getUom() {
        return uom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.UOM
     *
     * @param uom the value for public.ORDER_DETAIL.UOM
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setUom(String uom) {
        this.uom = uom == null ? null : uom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.CREATION_DATE
     *
     * @return the value of public.ORDER_DETAIL.CREATION_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.CREATION_DATE
     *
     * @param creationDate the value for public.ORDER_DETAIL.CREATION_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.CREATED_BY
     *
     * @return the value of public.ORDER_DETAIL.CREATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.CREATED_BY
     *
     * @param createdBy the value for public.ORDER_DETAIL.CREATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.LAST_UPDATE_DATE
     *
     * @return the value of public.ORDER_DETAIL.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for public.ORDER_DETAIL.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ORDER_DETAIL.LAST_UPDATED_BY
     *
     * @return the value of public.ORDER_DETAIL.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ORDER_DETAIL.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for public.ORDER_DETAIL.LAST_UPDATED_BY
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy == null ? null : lastUpdatedBy.trim();
    }
}