package com.dualwisdom.om.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public OrderMainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderKeyIsNull() {
            addCriterion("\"ORDER_KEY\" is null");
            return (Criteria) this;
        }

        public Criteria andOrderKeyIsNotNull() {
            addCriterion("\"ORDER_KEY\" is not null");
            return (Criteria) this;
        }

        public Criteria andOrderKeyEqualTo(String value) {
            addCriterion("\"ORDER_KEY\" =", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyNotEqualTo(String value) {
            addCriterion("\"ORDER_KEY\" <>", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyGreaterThan(String value) {
            addCriterion("\"ORDER_KEY\" >", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyGreaterThanOrEqualTo(String value) {
            addCriterion("\"ORDER_KEY\" >=", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyLessThan(String value) {
            addCriterion("\"ORDER_KEY\" <", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyLessThanOrEqualTo(String value) {
            addCriterion("\"ORDER_KEY\" <=", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyLike(String value) {
            addCriterion("\"ORDER_KEY\" like", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyNotLike(String value) {
            addCriterion("\"ORDER_KEY\" not like", value, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyIn(List<String> values) {
            addCriterion("\"ORDER_KEY\" in", values, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyNotIn(List<String> values) {
            addCriterion("\"ORDER_KEY\" not in", values, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyBetween(String value1, String value2) {
            addCriterion("\"ORDER_KEY\" between", value1, value2, "orderKey");
            return (Criteria) this;
        }

        public Criteria andOrderKeyNotBetween(String value1, String value2) {
            addCriterion("\"ORDER_KEY\" not between", value1, value2, "orderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyIsNull() {
            addCriterion("\"EXTERN_ORDER_KEY\" is null");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyIsNotNull() {
            addCriterion("\"EXTERN_ORDER_KEY\" is not null");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyEqualTo(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" =", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyNotEqualTo(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" <>", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyGreaterThan(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" >", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyGreaterThanOrEqualTo(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" >=", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyLessThan(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" <", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyLessThanOrEqualTo(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" <=", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyLike(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" like", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyNotLike(String value) {
            addCriterion("\"EXTERN_ORDER_KEY\" not like", value, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyIn(List<String> values) {
            addCriterion("\"EXTERN_ORDER_KEY\" in", values, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyNotIn(List<String> values) {
            addCriterion("\"EXTERN_ORDER_KEY\" not in", values, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyBetween(String value1, String value2) {
            addCriterion("\"EXTERN_ORDER_KEY\" between", value1, value2, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andExternOrderKeyNotBetween(String value1, String value2) {
            addCriterion("\"EXTERN_ORDER_KEY\" not between", value1, value2, "externOrderKey");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberIsNull() {
            addCriterion("\"CUSTOMER_NUMBER\" is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberIsNotNull() {
            addCriterion("\"CUSTOMER_NUMBER\" is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberEqualTo(String value) {
            addCriterion("\"CUSTOMER_NUMBER\" =", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberNotEqualTo(String value) {
            addCriterion("\"CUSTOMER_NUMBER\" <>", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberGreaterThan(String value) {
            addCriterion("\"CUSTOMER_NUMBER\" >", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberGreaterThanOrEqualTo(String value) {
            addCriterion("\"CUSTOMER_NUMBER\" >=", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberLessThan(String value) {
            addCriterion("\"CUSTOMER_NUMBER\" <", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberLessThanOrEqualTo(String value) {
            addCriterion("\"CUSTOMER_NUMBER\" <=", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberLike(String value) {
            addCriterion("\"CUSTOMER_NUMBER\" like", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberNotLike(String value) {
            addCriterion("\"CUSTOMER_NUMBER\" not like", value, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberIn(List<String> values) {
            addCriterion("\"CUSTOMER_NUMBER\" in", values, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberNotIn(List<String> values) {
            addCriterion("\"CUSTOMER_NUMBER\" not in", values, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberBetween(String value1, String value2) {
            addCriterion("\"CUSTOMER_NUMBER\" between", value1, value2, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNumberNotBetween(String value1, String value2) {
            addCriterion("\"CUSTOMER_NUMBER\" not between", value1, value2, "customerNumber");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("\"CUSTOMER_NAME\" is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("\"CUSTOMER_NAME\" is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("\"CUSTOMER_NAME\" =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("\"CUSTOMER_NAME\" <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("\"CUSTOMER_NAME\" >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("\"CUSTOMER_NAME\" >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("\"CUSTOMER_NAME\" <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("\"CUSTOMER_NAME\" <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("\"CUSTOMER_NAME\" like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("\"CUSTOMER_NAME\" not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("\"CUSTOMER_NAME\" in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("\"CUSTOMER_NAME\" not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("\"CUSTOMER_NAME\" between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("\"CUSTOMER_NAME\" not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1IsNull() {
            addCriterion("\"SHIP_TO_ADDR1\" is null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1IsNotNull() {
            addCriterion("\"SHIP_TO_ADDR1\" is not null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1EqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR1\" =", value, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1NotEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR1\" <>", value, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1GreaterThan(String value) {
            addCriterion("\"SHIP_TO_ADDR1\" >", value, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1GreaterThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR1\" >=", value, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1LessThan(String value) {
            addCriterion("\"SHIP_TO_ADDR1\" <", value, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1LessThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR1\" <=", value, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1Like(String value) {
            addCriterion("\"SHIP_TO_ADDR1\" like", value, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1NotLike(String value) {
            addCriterion("\"SHIP_TO_ADDR1\" not like", value, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1In(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR1\" in", values, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1NotIn(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR1\" not in", values, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1Between(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR1\" between", value1, value2, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr1NotBetween(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR1\" not between", value1, value2, "shipToAddr1");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2IsNull() {
            addCriterion("\"SHIP_TO_ADDR2\" is null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2IsNotNull() {
            addCriterion("\"SHIP_TO_ADDR2\" is not null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2EqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR2\" =", value, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2NotEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR2\" <>", value, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2GreaterThan(String value) {
            addCriterion("\"SHIP_TO_ADDR2\" >", value, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2GreaterThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR2\" >=", value, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2LessThan(String value) {
            addCriterion("\"SHIP_TO_ADDR2\" <", value, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2LessThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR2\" <=", value, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2Like(String value) {
            addCriterion("\"SHIP_TO_ADDR2\" like", value, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2NotLike(String value) {
            addCriterion("\"SHIP_TO_ADDR2\" not like", value, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2In(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR2\" in", values, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2NotIn(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR2\" not in", values, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2Between(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR2\" between", value1, value2, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr2NotBetween(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR2\" not between", value1, value2, "shipToAddr2");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3IsNull() {
            addCriterion("\"SHIP_TO_ADDR3\" is null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3IsNotNull() {
            addCriterion("\"SHIP_TO_ADDR3\" is not null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3EqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR3\" =", value, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3NotEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR3\" <>", value, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3GreaterThan(String value) {
            addCriterion("\"SHIP_TO_ADDR3\" >", value, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3GreaterThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR3\" >=", value, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3LessThan(String value) {
            addCriterion("\"SHIP_TO_ADDR3\" <", value, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3LessThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR3\" <=", value, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3Like(String value) {
            addCriterion("\"SHIP_TO_ADDR3\" like", value, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3NotLike(String value) {
            addCriterion("\"SHIP_TO_ADDR3\" not like", value, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3In(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR3\" in", values, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3NotIn(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR3\" not in", values, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3Between(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR3\" between", value1, value2, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr3NotBetween(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR3\" not between", value1, value2, "shipToAddr3");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4IsNull() {
            addCriterion("\"SHIP_TO_ADDR4\" is null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4IsNotNull() {
            addCriterion("\"SHIP_TO_ADDR4\" is not null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4EqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR4\" =", value, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4NotEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR4\" <>", value, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4GreaterThan(String value) {
            addCriterion("\"SHIP_TO_ADDR4\" >", value, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4GreaterThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR4\" >=", value, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4LessThan(String value) {
            addCriterion("\"SHIP_TO_ADDR4\" <", value, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4LessThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR4\" <=", value, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4Like(String value) {
            addCriterion("\"SHIP_TO_ADDR4\" like", value, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4NotLike(String value) {
            addCriterion("\"SHIP_TO_ADDR4\" not like", value, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4In(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR4\" in", values, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4NotIn(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR4\" not in", values, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4Between(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR4\" between", value1, value2, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr4NotBetween(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR4\" not between", value1, value2, "shipToAddr4");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5IsNull() {
            addCriterion("\"SHIP_TO_ADDR5\" is null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5IsNotNull() {
            addCriterion("\"SHIP_TO_ADDR5\" is not null");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5EqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR5\" =", value, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5NotEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR5\" <>", value, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5GreaterThan(String value) {
            addCriterion("\"SHIP_TO_ADDR5\" >", value, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5GreaterThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR5\" >=", value, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5LessThan(String value) {
            addCriterion("\"SHIP_TO_ADDR5\" <", value, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5LessThanOrEqualTo(String value) {
            addCriterion("\"SHIP_TO_ADDR5\" <=", value, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5Like(String value) {
            addCriterion("\"SHIP_TO_ADDR5\" like", value, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5NotLike(String value) {
            addCriterion("\"SHIP_TO_ADDR5\" not like", value, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5In(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR5\" in", values, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5NotIn(List<String> values) {
            addCriterion("\"SHIP_TO_ADDR5\" not in", values, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5Between(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR5\" between", value1, value2, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andShipToAddr5NotBetween(String value1, String value2) {
            addCriterion("\"SHIP_TO_ADDR5\" not between", value1, value2, "shipToAddr5");
            return (Criteria) this;
        }

        public Criteria andEtdIsNull() {
            addCriterion("\"ETD\" is null");
            return (Criteria) this;
        }

        public Criteria andEtdIsNotNull() {
            addCriterion("\"ETD\" is not null");
            return (Criteria) this;
        }

        public Criteria andEtdEqualTo(Date value) {
            addCriterion("\"ETD\" =", value, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdNotEqualTo(Date value) {
            addCriterion("\"ETD\" <>", value, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdGreaterThan(Date value) {
            addCriterion("\"ETD\" >", value, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdGreaterThanOrEqualTo(Date value) {
            addCriterion("\"ETD\" >=", value, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdLessThan(Date value) {
            addCriterion("\"ETD\" <", value, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdLessThanOrEqualTo(Date value) {
            addCriterion("\"ETD\" <=", value, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdIn(List<Date> values) {
            addCriterion("\"ETD\" in", values, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdNotIn(List<Date> values) {
            addCriterion("\"ETD\" not in", values, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdBetween(Date value1, Date value2) {
            addCriterion("\"ETD\" between", value1, value2, "etd");
            return (Criteria) this;
        }

        public Criteria andEtdNotBetween(Date value1, Date value2) {
            addCriterion("\"ETD\" not between", value1, value2, "etd");
            return (Criteria) this;
        }

        public Criteria andEtaIsNull() {
            addCriterion("\"ETA\" is null");
            return (Criteria) this;
        }

        public Criteria andEtaIsNotNull() {
            addCriterion("\"ETA\" is not null");
            return (Criteria) this;
        }

        public Criteria andEtaEqualTo(Date value) {
            addCriterion("\"ETA\" =", value, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaNotEqualTo(Date value) {
            addCriterion("\"ETA\" <>", value, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaGreaterThan(Date value) {
            addCriterion("\"ETA\" >", value, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaGreaterThanOrEqualTo(Date value) {
            addCriterion("\"ETA\" >=", value, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaLessThan(Date value) {
            addCriterion("\"ETA\" <", value, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaLessThanOrEqualTo(Date value) {
            addCriterion("\"ETA\" <=", value, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaIn(List<Date> values) {
            addCriterion("\"ETA\" in", values, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaNotIn(List<Date> values) {
            addCriterion("\"ETA\" not in", values, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaBetween(Date value1, Date value2) {
            addCriterion("\"ETA\" between", value1, value2, "eta");
            return (Criteria) this;
        }

        public Criteria andEtaNotBetween(Date value1, Date value2) {
            addCriterion("\"ETA\" not between", value1, value2, "eta");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateIsNull() {
            addCriterion("\"INVOICE_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateIsNotNull() {
            addCriterion("\"INVOICE_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateEqualTo(Date value) {
            addCriterion("\"INVOICE_DATE\" =", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateNotEqualTo(Date value) {
            addCriterion("\"INVOICE_DATE\" <>", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateGreaterThan(Date value) {
            addCriterion("\"INVOICE_DATE\" >", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"INVOICE_DATE\" >=", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateLessThan(Date value) {
            addCriterion("\"INVOICE_DATE\" <", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateLessThanOrEqualTo(Date value) {
            addCriterion("\"INVOICE_DATE\" <=", value, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateIn(List<Date> values) {
            addCriterion("\"INVOICE_DATE\" in", values, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateNotIn(List<Date> values) {
            addCriterion("\"INVOICE_DATE\" not in", values, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateBetween(Date value1, Date value2) {
            addCriterion("\"INVOICE_DATE\" between", value1, value2, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceDateNotBetween(Date value1, Date value2) {
            addCriterion("\"INVOICE_DATE\" not between", value1, value2, "invoiceDate");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberIsNull() {
            addCriterion("\"INVOICE_NUMBER\" is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberIsNotNull() {
            addCriterion("\"INVOICE_NUMBER\" is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberEqualTo(String value) {
            addCriterion("\"INVOICE_NUMBER\" =", value, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberNotEqualTo(String value) {
            addCriterion("\"INVOICE_NUMBER\" <>", value, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberGreaterThan(String value) {
            addCriterion("\"INVOICE_NUMBER\" >", value, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberGreaterThanOrEqualTo(String value) {
            addCriterion("\"INVOICE_NUMBER\" >=", value, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberLessThan(String value) {
            addCriterion("\"INVOICE_NUMBER\" <", value, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberLessThanOrEqualTo(String value) {
            addCriterion("\"INVOICE_NUMBER\" <=", value, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberLike(String value) {
            addCriterion("\"INVOICE_NUMBER\" like", value, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberNotLike(String value) {
            addCriterion("\"INVOICE_NUMBER\" not like", value, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberIn(List<String> values) {
            addCriterion("\"INVOICE_NUMBER\" in", values, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberNotIn(List<String> values) {
            addCriterion("\"INVOICE_NUMBER\" not in", values, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberBetween(String value1, String value2) {
            addCriterion("\"INVOICE_NUMBER\" between", value1, value2, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andInvoiceNumberNotBetween(String value1, String value2) {
            addCriterion("\"INVOICE_NUMBER\" not between", value1, value2, "invoiceNumber");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNull() {
            addCriterion("\"CREATION_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andCreationDateIsNotNull() {
            addCriterion("\"CREATION_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDateEqualTo(Date value) {
            addCriterion("\"CREATION_DATE\" =", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotEqualTo(Date value) {
            addCriterion("\"CREATION_DATE\" <>", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThan(Date value) {
            addCriterion("\"CREATION_DATE\" >", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"CREATION_DATE\" >=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThan(Date value) {
            addCriterion("\"CREATION_DATE\" <", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("\"CREATION_DATE\" <=", value, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateIn(List<Date> values) {
            addCriterion("\"CREATION_DATE\" in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotIn(List<Date> values) {
            addCriterion("\"CREATION_DATE\" not in", values, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateBetween(Date value1, Date value2) {
            addCriterion("\"CREATION_DATE\" between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("\"CREATION_DATE\" not between", value1, value2, "creationDate");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("\"CREATED_BY\" is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("\"CREATED_BY\" is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("\"CREATED_BY\" =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("\"CREATED_BY\" <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("\"CREATED_BY\" >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("\"CREATED_BY\" >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("\"CREATED_BY\" <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("\"CREATED_BY\" <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("\"CREATED_BY\" like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("\"CREATED_BY\" not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("\"CREATED_BY\" in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("\"CREATED_BY\" not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("\"CREATED_BY\" between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("\"CREATED_BY\" not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("\"LAST_UPDATE_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("\"LAST_UPDATE_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("\"LAST_UPDATE_DATE\" <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("\"LAST_UPDATE_DATE\" in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("\"LAST_UPDATE_DATE\" not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("\"LAST_UPDATE_DATE\" between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("\"LAST_UPDATE_DATE\" not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNull() {
            addCriterion("\"LAST_UPDATED_BY\" is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIsNotNull() {
            addCriterion("\"LAST_UPDATED_BY\" is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByEqualTo(String value) {
            addCriterion("\"LAST_UPDATED_BY\" =", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotEqualTo(String value) {
            addCriterion("\"LAST_UPDATED_BY\" <>", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThan(String value) {
            addCriterion("\"LAST_UPDATED_BY\" >", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("\"LAST_UPDATED_BY\" >=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThan(String value) {
            addCriterion("\"LAST_UPDATED_BY\" <", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("\"LAST_UPDATED_BY\" <=", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByLike(String value) {
            addCriterion("\"LAST_UPDATED_BY\" like", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotLike(String value) {
            addCriterion("\"LAST_UPDATED_BY\" not like", value, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByIn(List<String> values) {
            addCriterion("\"LAST_UPDATED_BY\" in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotIn(List<String> values) {
            addCriterion("\"LAST_UPDATED_BY\" not in", values, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByBetween(String value1, String value2) {
            addCriterion("\"LAST_UPDATED_BY\" between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedByNotBetween(String value1, String value2) {
            addCriterion("\"LAST_UPDATED_BY\" not between", value1, value2, "lastUpdatedBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated do_not_delete_during_merge Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.ORDER_MAIN
     *
     * @mbggenerated Sat Jun 11 01:04:59 GMT+08:00 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}